### ISSUE TITLE
v3.3.0 unable to load map files?

### ISSUE THREAD

**Issue by Frankfires** [TheBoneJarmer/TiledCS#87]
I'm straight up confused. Things were working fine right before I updated, if I downgrade back to v3.2.3 things work fine again.
![image](https://user-images.githubusercontent.com/67832033/185754753-86189401-d9df-473e-a800-cfb74a9c5f2a.png)

**Comment by TheBoneJarmer** [comment]
That is definitely not good. Could you send the whole stacktrace please?

**Comment by Frankfires** [comment]
```
TiledCS.TiledException
  HResult=0x80131500
  Message=An error occurred while trying to parse the Tiled map file
  Source=TiledCS
  StackTrace:
   at TiledCS.TiledMap.ParseXml(String xml)
   at Static.Utilities.InGame.Initialize() in C:\Users\nicol\Desktop\Static\Game\Static\Static\Utilities\Menu.cs:line 49
   at Static.Utilities.Menu..ctor() in C:\Users\nicol\Desktop\Static\Game\Static\Static\Utilities\Menu.cs:line 19
   at Static.Utilities.InGame..ctor()
   at Static.Static.Initialize() in C:\Users\nicol\Desktop\Static\Game\Static\Static\Static.cs:line 48
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Static.Program.Main() in C:\Users\nicol\Desktop\Static\Game\Static\Static\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by TheBoneJarmer** [comment]
Thanks! Does the inner exception have a stacktrace by any chance? Because unfortunately this says fuck to me haha

**Comment by pacoo2454** [comment]
I am getting the same error when I have an object layer in the tilemap.

**Comment by TheBoneJarmer** [comment]
Hey @pacoo2454 

Thanks for the heads up about the object layer. I didn't had one in my test map **anymore** so I just added one and it went kaboom for me too. So I patched it up and a new version should be on its way in a couple of minutes. :)

With kind regards,
TheBoneJarmer

**Comment by Frankfires** [comment]
I've updated to 3.3.1 things seem to be working flawlessly ( so far ) 👍

**Comment by pacoo2454** [comment]
No problem. That also fixed it for me too! Thanks for the quick update.

**Comment by TheBoneJarmer** [comment]
Awesome! Glad it works for the both of you. :D
